### ISSUE TITLE
Errors in running install_SG.sh

### ISSUE THREAD

**Issue by rmmomin** [OpenSourceEcon/BootCamp2019#21]
@rickecon @janertl @rebekahanne 

While running ./install_SG.sh on the Midway cluster, the script terminates with the error below. As a result, I receive an error trying to run OSE2019/day1/SparseGridCode/analytical_examples/TASMANIAN_Python/OSE_example.py

Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    import numpy
ImportError: No module named numpy
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    import numpy
ImportError: No module named numpy
Traceback (most recent call last):
  File "hs071.py", line 6, in <module>
    import pyipopt
ImportError: No module named pyipopt
 PYIPOPT is tested and installed
 IPOPT and PYIPOPT is installed

**Comment by rickecon** [comment]
@sischei and @azinoma can you look at this question from @rmmomin? This doesn't make sense to me why there is a `numpy` error.

**Comment by rebekahanne** [comment]
@rmmomin One quick fix for me was to load in the anaconda module. This is probably overkill.

**Comment by ozaltun** [comment]
I installed the python 3.5.2 using:

module load python/3.5.2

**Comment by azinoma** [comment]
Some scripts still use python 2 at some parts, so it may be better do 
module load python
, which will load python/2.7.12

**Comment by ozaltun** [comment]
In case you want a more interactive view, you can run jupyter notebook using the cluster. Instructions can be found:

https://rcc.uchicago.edu/docs/software/environments/python/index.html
